name: Hello Action
description: "Greet someone and record time"

inputs:
  who_to_greet:
    description: "Who to greet"
    # required: true
    default: "World"

outputs:
  time:
    description: "The time of the greeting"

runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'linux'
