name: Slack Webhook
inputs:
  slack_webhook:
    required: true
  message:
    required: true
runs:
  using: docker
  image: "Dockerfile"
  args: 
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.message }}
