name: Hello Action
description: "Greet someone and record time"

inputs:
  who_to_greet:
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  time:
    description: "The time of the greeting"

runs:
  using: "node16"
  main: "dist/index.js"
