name: Docker

on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:23-alpine3.19
            #if the image is private
            # credentials:
                # username:
                # password:
            env:
                API_URL: some-url.com

            ports:
                - 80
        steps:
            - name: Log Node and OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some text' > text.txt
            - name: Container in a step
              uses: docker://node:23-alpine3.19
              with:
                entrypoint: /usr/local/bin/node
                args: -p 1+3
            - name: Log node verison
              uses: docker://node:23-alpine3.19
              with:
                args: -v
            - name: Show file contents
              uses: docker://node:23-alpine3.19
              with:
                entrypoint: cat
                args: text.txt
            # - uses: actions/checkout@v3
            # - name: Run a bash script
            #   uses: docker://node:23-alpine3.19
            #   with:
            #     entrypoint: ./script.sh
            #     args: "This is argument passed to a script placed in the root dir"
            - name: Send a slack message
              uses: docker://technosophos/slack-notify
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}    #this SLACK_WEBHOOK has been added as the repo secret using github cli
                SLACK_TITLE: From Github Actions
                SLACK_MESSAGE: "Actor: ${{github.actor}}, Event: ${{github.event_name}}"
                SLACK_COLOR: "#723fc4"
 