name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]

run-name: "Expressions and Contexts by @${{ github.actor }}, event: ${{ github.event_name}}"  #This will make sure that the name of the workflow remains only this and change only the values of username and events happened.

jobs:
    runs-on-issues-and-prs:
        runs-on: ubuntu-latest
        if: contains(fromJson('["issues","pull_request"]'), github.event_name)
        steps:
            - name: Run only if issue has a bug label
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}
    using-expressions-and-contexts:
        runs-on: ubuntu-latest 
        if: github.event_name == 'push'      #If the event is any other than push then the job will be skipped.  
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump Contexts
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'