name: External Events
on:
    repository_dispatch:
        types: [build]


jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Repo dispatch"
            - run: eho ${{ github.event.client_payload.env}}